name: fluttermodule
description: A new Flutter module.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
#  #网络
  dio: ^3.0.7
#  #  webview
  webview_flutter: ^2.0.2
  webview_cookie_manager: ^1.0.5
#  状态管理
#    provider: ^3.2.0
  flutter_bloc: ^6.1.1
#
#  #工具类
  common_utils: ^1.2.1

  #  图片
  cached_network_image: ^2.0.0-rc.1
    #如果package get报错,改成下面的版本
    #  cached_network_image: ^2.0.0-rc.1

    #  banner
  flutter_swiper: ^1.1.6

    #标签加载,类似html
  flutter_html: ^0.11.0

    #语言包
  flutter_localizations:
      sdk: flutter
    #相机相册-注销,导致打包失败
    #  image_picker: ^0.6.3+1

    #包信息
  package_info: ^0.4.0+17

  url_launcher: ^5.4.5

    #视频播放切勿改动
    #  chewie: ^0.9.8+1 项目中已把chewie的源码拿出来改动过了,请不要再次dependencie
  video_player: ^0.10.10

    #shared_preferences插件
  shared_preferences: ^0.5.12+4

#  screen: ^0.0.5

  open_iconic_flutter: ^0.3.0

  english_words: ^3.1.5

    #下拉菜单
  dropdown_menu: ^1.1.1

    #与安卓原生交互必须的库
  flutter_plugin_android_lifecycle: ^1.0.7

    #  瀑布流
  flutter_staggered_grid_view: ^0.3.2

  flutter_screenutil: ^4.0.3+3

    #二维码
  qr_flutter: ^3.2.0
  intl: any



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/mine/
    - assets/images/friends/
    - assets/images/posts/
    - assets/images/saved/
    - assets/images/story/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.cx580.fluttermodule
    iosBundleIdentifier: com.cx580.fluttermodule
