source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterAtiOSDemo' do
    
    use_frameworks!
    #不带：path  的pod install 成功后会生成Pods 文件夹，里面都是远端github的库
    #pod 'AFNetworking'

  # Pods for iOSFlutterHybrid
    install_all_flutter_pods(flutter_application_path)


end
